### ISSUE TITLE
Access to Google Authentication

### ISSUE THREAD

**Issue by rcefalu10** [danielgsmith/regions-investor#29]

**Comment by danielgsmith** [comment]
OAuth Token Generated for use with Google Authentication Services for use on localhost:3000

Credential:
Client ID: 1022136605161-0fhp8uhuhe73rra587t5v33835qpncsn.apps.googleusercontent.com
Client secret: yeB3PSLNHel3bNTcRqE98jhB
Creation date: August 30, 2020 at 6:54:15 PM GMT-4
