### ISSUE TITLE
Make sure everyone is onboarded to zenhub/github correctly

### ISSUE THREAD

**Issue by rcefalu10** [danielgsmith/regions-investor#3]
https://app.zenhub.com/workspaces/0137-junior-design-5f409160b2da6c0012d8caec/board - zenhub link

https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/related - zenhub extension

https://github.com/regions-junior-design/regions-investor - github

**Comment by rcefalu10** [comment]
Please type in here when you have everything set up correctly

**Comment by SiddharthBalireddy** [comment]
done

**Comment by hsmith307** [comment]
done

**Comment by rcefalu10** [comment]
looks like everyone is done
